### PR TITLE
Upgrade ActiveSupport dependency

### PR DESCRIPTION
**Pull request by darioghilardi**
This PR upgrades the ActiveSupport dependency in order to use the gem on Rails 4.

### CODE REVIEW

**Comment by daniel-rikowski** [comment]
What is the status of this? Is there additional help needed? (Tests, feedback, etc.)

ActiveSupport 3.2 is practically unmaintained, it only receives updates for severe security issues (http://guides.rubyonrails.org/maintenance_policy.html) So if someone is using one of the maintained ActiveSupport versions (4.x) then version 1.0.0 is the only usable release of this gem.

Also Rails 5 is around the corner. (http://weblog.rubyonrails.org/2015/4/25/this-week-in-rails-railsconf-2015-edition/)

Considering the range of versions of ActiveSupport, IMHO the dependency should be relaxed to `>= 3.0` instead of `~> 4.0`. That way all users stuck with 3.x versions could still use this gem without shutting out the 4.x and eventually the 5.x users.

**Comment by mattab** [comment]
Hi @daniel-rikowski  @darioghilardi 

Our current Ruby SDK maintainer is @Achillefs  but maybe you would like to help maintain this project? It would be awesome to get your help to maintain the Ruby library and make it awesome for all Piwik users :+1:

**Comment by daniel-rikowski** [comment]
@mattab I definitly like to help out. What kind of help do you require?

**Comment by mattab** [comment]
@daniel-rikowski Great to hear :-) 

Maintaining an official Piwik SDK includes the following responsabilities:
 * Reading bug reports and replying to users (ask more information, check if the bug is valid, etc.)
 * Reviewing pull requests that users create to foster collaboration
 * Update the SDK to match latest [Piwik Tracking API](http://developer.piwik.org/api-reference/tracking-api) capabilities
 * Improve README and examples on how to use the library
 * and any other thing you may find useful or interesting :-)

What do you think?

**Comment by daniel-rikowski** [comment]
That sounds perfectly reasonable. I can't promise I'll find much time to do coding, though, but I'll gladly look after bug reports and pull requests.

Sign me up :smiley:

**Comment by mattab** [comment]
Hi @daniel-rikowski 

Great to hear :-) 

you are now a collaborator on this repository. Thank you for your future contributions! 

(CC maintainer of Ruby SDK @Achillefs )

**Comment by sidazhou** [comment]
Is it confirmed to be OK to update from ('activesupport','~> 3.0') to ('activesupport','~> 4.0') ?

**Comment by daniel-rikowski** [comment]
@sidazhou Basically yes but I don't want to shut out the users still locked at activesupport 3. (Rails 3.2.x users for example) I think there is no reason to raise the minimum required version to 4.0

@darioghilardi Since you created this pull request, would you change the dependency requirements to `">= 3.0", "< 5.0"`? Then I'll merge your pull request asap.

**Comment by sidazhou** [comment]
Using 'activesupport','~> 4.0' so far so good.

**Comment by daniel-rikowski** [comment]
Closing in favor of #16

**Pull request closed without merging**
